--------------------------------------------
Creating a User document and show validation
--------------------------------------------

  Attempting validation on:

    {"_types": ["User"], "secret": "whatevz", "name": "test hash", "_cls": "User"}

  DictPunch caught: secret(whatevz):  MD5 value is wrong length

  Adjusted invalid data and trying again on:

    {"_types": ["User"], "secret": "e8b5d682452313a6142c10b045a9a135", "name": "test hash", "_cls": "User"}

  Validation passed

----------------------------------------------------------------
Converting a Python dictionary to a User document for validation
----------------------------------------------------------------

  Attempting validation on:

    {'rogue_field': 'MWAHAHA', 'bio': 'J2D2 loves music', 'secret': 'e8b5d682452313a6142c10b045a9a135', 'name': 'J2D2'}

  Checking for *any* exceptions:  Validation passed
  Checking for *every* exception:  Validation passed

  Document as Python:
    {'_types': ['User'], 'bio': u'J2D2 loves music', 'secret': 'e8b5d682452313a6142c10b045a9a135', 'name': u'J2D2', '_cls': 'User'}

  Owner safe doc:
    {"bio": "J2D2 loves music", "secret": "e8b5d682452313a6142c10b045a9a135", "name": "J2D2"}

  Public safe doc:
    {"name": "J2D2"}

